# Generated by Django 2.2.6 on 2019-12-05 18:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auditurium',
            fields=[
                ('name', models.CharField(max_length=25, primary_key=True, serialize=False, verbose_name='Название')),
                ('address', models.CharField(max_length=100, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Аудитория',
                'verbose_name_plural': 'Аудитории',
            },
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('did', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=25, primary_key=True, serialize=False, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Дисциплина',
                'verbose_name_plural': 'Дисциплины',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('gid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=25, primary_key=True, serialize=False, verbose_name='Название')),
                ('workload', models.FloatField(verbose_name='Нагрузка')),
                ('people_count', models.IntegerField(verbose_name='Количество учащихся')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('tid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Имя')),
                ('workload', models.FloatField(verbose_name='Нагрузка')),
                ('auditurium', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Auditurium', verbose_name='Аудитория')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Discipline', verbose_name='Профиль')),
            ],
            options={
                'verbose_name': 'Преподаватель',
                'verbose_name_plural': 'Преподаватели',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('lid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lesson_number', models.IntegerField(verbose_name='Номер занятия')),
                ('day', models.IntegerField(verbose_name='День')),
                ('data', models.DateField(auto_now_add=True, verbose_name='дата создания')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Group', verbose_name='Группа')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Teacher', verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Занятие',
                'verbose_name_plural': 'Занятия',
            },
        ),
    ]
