# Generated by Django 2.2.6 on 2019-12-17 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auditurium',
            fields=[
                ('name', models.CharField(max_length=25, primary_key=True, serialize=False, verbose_name='Название')),
                ('address', models.CharField(max_length=100, verbose_name='Адрес')),
                ('capacity', models.IntegerField(default=0, verbose_name='Вместимость')),
            ],
            options={
                'verbose_name': 'Аудитория',
                'verbose_name_plural': 'Аудитории',
            },
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('did', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Дисциплина',
                'verbose_name_plural': 'Дисциплины',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('gid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25, verbose_name='Название')),
                ('people_count', models.IntegerField(default=0, verbose_name='Количество учащихся')),
                ('max_lessons', models.IntegerField(default=0, verbose_name='Максимум занятий')),
                ('max_repeat_lessons', models.IntegerField(default=0, verbose_name='Максимум одинаковых занятий')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
        migrations.CreateModel(
            name='Shedule',
            fields=[
                ('sid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fourth', models.IntegerField(default=0, verbose_name='Четверть')),
                ('period', models.CharField(default='None', max_length=10, verbose_name='Период')),
                ('date', models.DateField(auto_now_add=True, verbose_name='дата создания')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Расписание',
                'verbose_name_plural': 'Расписания',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('tid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Имя')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Discipline', verbose_name='Профиль')),
                ('shedule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Shedule', verbose_name='Расписание')),
            ],
            options={
                'verbose_name': 'Преподаватель',
                'verbose_name_plural': 'Преподаватели',
            },
        ),
        migrations.CreateModel(
            name='TimeLesson',
            fields=[
                ('tid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.IntegerField(verbose_name='Номер занятия')),
                ('start', models.TimeField(verbose_name='Начало')),
                ('end', models.TimeField(verbose_name='Конец')),
                ('day_week', models.IntegerField(verbose_name='День недели')),
                ('shedule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Shedule', verbose_name='Расписание')),
            ],
            options={
                'verbose_name': 'Звонок',
                'verbose_name_plural': 'Звонки',
            },
        ),
        migrations.CreateModel(
            name='TeacherSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tsid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('business', models.BooleanField(default=False, verbose_name='Занятость')),
                ('lesson_time', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.TimeLesson', verbose_name='Время урока')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Teacher', verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Расписание преподавателей',
                'verbose_name_plural': 'Расписания преподавателей',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('lid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.IntegerField(default=0, verbose_name='Номер')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Group', verbose_name='Группа')),
                ('shedule', models.ForeignKey(null='True', on_delete=django.db.models.deletion.CASCADE, to='backend.Shedule', verbose_name='Расписание')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Teacher', verbose_name='Преподаватель')),
                ('time', models.ForeignKey(null='True', on_delete=django.db.models.deletion.CASCADE, to='backend.TimeLesson', verbose_name='Звонок')),
            ],
            options={
                'verbose_name': 'Занятие',
                'verbose_name_plural': 'Занятия',
            },
        ),
        migrations.CreateModel(
            name='GroupWorkload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gwid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('amount', models.IntegerField(default=0, verbose_name='Количество уроков в неделю')),
                ('discipline', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Discipline', verbose_name='Дисциплина')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Group', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Загруженность групп',
                'verbose_name_plural': 'Загруженности групп',
            },
        ),
        migrations.CreateModel(
            name='GroupShedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gsid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('business', models.BooleanField(default=False, verbose_name='Занятость')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Group', verbose_name='Группа')),
                ('lesson_time', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.TimeLesson', verbose_name='Время урока')),
            ],
            options={
                'verbose_name': 'Расписание групп',
                'verbose_name_plural': 'Расписания групп',
            },
        ),
        migrations.AddField(
            model_name='group',
            name='shedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Shedule', verbose_name='Расписание'),
        ),
        migrations.AddField(
            model_name='discipline',
            name='shedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Shedule', verbose_name='Расписание'),
        ),
        migrations.CreateModel(
            name='AudituriumSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('business', models.BooleanField(default=False, verbose_name='Занятость')),
                ('auditurium', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Auditurium', verbose_name='Аудитория')),
                ('lesson_time', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.TimeLesson', verbose_name='Время урока')),
            ],
            options={
                'verbose_name': 'Расписание аудитории',
                'verbose_name_plural': 'Расписания аудитории',
            },
        ),
    ]
