# Generated by Django 2.2.6 on 2019-12-13 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='max_lessons',
            field=models.IntegerField(default=0, verbose_name='Максимум занятий'),
        ),
        migrations.AddField(
            model_name='group',
            name='max_same_lessons',
            field=models.IntegerField(default=0, verbose_name='Максимум одинаковых занятий'),
        ),
        migrations.AddField(
            model_name='group',
            name='people_count',
            field=models.IntegerField(default=0, verbose_name='Количество учащихся'),
        ),
    ]
