# Generated by Django 2.2.6 on 2019-12-06 03:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeLesson',
            fields=[
                ('tid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.IntegerField(verbose_name='Номер занятия')),
                ('start', models.TimeField(verbose_name='Начало')),
                ('end', models.TimeField(verbose_name='Конец')),
                ('breaks', models.IntegerField(verbose_name='Перерыв')),
                ('day_week', models.IntegerField(verbose_name='День недели')),
            ],
            options={
                'verbose_name': 'Звонок',
                'verbose_name_plural': 'Звонки',
            },
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='data',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='day',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='lesson_number',
        ),
        migrations.CreateModel(
            name='Shedule',
            fields=[
                ('sid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('date', models.DateField(auto_now_add=True, verbose_name='дата создания')),
                ('lessons', models.ManyToManyField(null=True, related_name='shedule_lesson', to='backend.Lesson', verbose_name='Уроки')),
            ],
            options={
                'verbose_name': 'Расписание',
                'verbose_name_plural': 'Расписания',
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='time',
            field=models.ForeignKey(null='True', on_delete=django.db.models.deletion.CASCADE, to='backend.TimeLesson', verbose_name='Звонок'),
            preserve_default='True',
        ),
    ]
