# Generated by Django 2.2.6 on 2019-12-13 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20191213_0934'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='max_same_lessons',
            new_name='max_repeat_lessons',
        ),
    ]
