# Generated by Django 2.2.6 on 2019-12-06 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20191206_0319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shedule',
            name='lessons',
            field=models.ManyToManyField(related_name='shedule_lesson', to='backend.Lesson', verbose_name='Уроки'),
        ),
    ]
