# Generated by Django 2.2.6 on 2019-12-20 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auditurium_shedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timelesson',
            name='day_week',
        ),
        migrations.AddField(
            model_name='lesson',
            name='day_week',
            field=models.IntegerField(default=1, verbose_name='День недели'),
        ),
    ]
