# Generated by Django 2.2.6 on 2019-12-20 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20191220_0711'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='auditurium',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Auditurium', verbose_name='Аудитория'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='discipline',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Discipline', verbose_name='Дисциплина'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='time',
            field=models.CharField(default='00:00', max_length=20, verbose_name='Звонок'),
        ),
    ]
