# Generated by Django 2.2.6 on 2019-12-13 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20191213_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='discipline',
            name='shedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Shedule', verbose_name='Расписание'),
        ),
    ]
