# Generated by Django 2.2.6 on 2019-12-13 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_discipline_shedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='workload',
        ),
    ]
