# Generated by Django 2.2.6 on 2019-12-15 15:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_remove_teacher_workload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='workload',
        ),
        migrations.AddField(
            model_name='auditurium',
            name='capacity',
            field=models.IntegerField(default=0, verbose_name='Вместимость'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='shedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Shedule', verbose_name='Расписание'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='auditurium',
            field=models.CharField(max_length=25, verbose_name='Аудитория'),
        ),
        migrations.CreateModel(
            name='TeacherSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tsid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('business', models.BooleanField(default=False, verbose_name='Занятость')),
                ('lesson_time', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.TimeLesson', verbose_name='Время урока')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Teacher', verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Расписание преподавателей',
                'verbose_name_plural': 'Расписания преподавателей',
            },
        ),
        migrations.CreateModel(
            name='GroupWorkload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gwid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('amount', models.IntegerField(default=0, verbose_name='Количество уроков в неделю')),
                ('discipline', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Discipline', verbose_name='Дисциплина')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Group', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Загруженность групп',
                'verbose_name_plural': 'Загруженности групп',
            },
        ),
        migrations.CreateModel(
            name='GroupShedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gsid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('business', models.BooleanField(default=False, verbose_name='Занятость')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Group', verbose_name='Группа')),
                ('lesson_time', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.TimeLesson', verbose_name='Время урока')),
            ],
            options={
                'verbose_name': 'Расписание групп',
                'verbose_name_plural': 'Расписания групп',
            },
        ),
        migrations.CreateModel(
            name='AudituriumSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('business', models.BooleanField(default=False, verbose_name='Занятость')),
                ('auditurium', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Auditurium', verbose_name='Аудитория')),
                ('lesson_time', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.TimeLesson', verbose_name='Время урока')),
            ],
            options={
                'verbose_name': 'Расписание аудитории',
                'verbose_name_plural': 'Расписания аудитории',
            },
        ),
    ]
