# Generated by Django 2.2.6 on 2019-12-20 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20191220_0920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditurium',
            name='address',
        ),
    ]
