# Generated by Django 2.2.6 on 2019-12-12 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20191210_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='shedule',
            name='fourth',
            field=models.IntegerField(default=0, verbose_name='Четверть'),
        ),
        migrations.AddField(
            model_name='shedule',
            name='period',
            field=models.CharField(default='None', max_length=10, verbose_name='Период'),
        ),
    ]
