# Generated by Django 2.2.6 on 2019-12-15 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20191215_1502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='auditurium',
        ),
    ]
