# Generated by Django 2.2.6 on 2019-12-12 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20191212_0700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shedule',
            name='name',
        ),
    ]
