# Generated by Django 2.2.6 on 2019-12-12 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_remove_shedule_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timelesson',
            name='breaks',
        ),
    ]
