# Generated by Django 2.2.6 on 2019-12-12 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_remove_timelesson_breaks'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelesson',
            name='shedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Shedule', verbose_name='Расписание'),
        ),
    ]
