# Generated by Django 2.2.6 on 2019-12-13 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_timelesson_shedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='people_count',
        ),
        migrations.AddField(
            model_name='group',
            name='shedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Shedule', verbose_name='Расписание'),
        ),
    ]
